name: Hra
version: 1.0
api-version: 1.13

main: mainHra.MainHra
commands:
  Duch:
  Golem:
  Lucistnik:
  Ohnivak:
  Vidlak:
    description: Vytvori teleportera pro vybavu ducha, golema, lucistnika, ohnivaka, vidlaka