name: Hra
version: 1.0
api-version: 1.13

main: mainHra.MainHra
commands:
  _Duch:
  _Golem:
  _Lucistnik:
  _Ohnivak:
  _Vidlak:
    description: Vytvori teleportera pro vybavu ducha, golema, lucistnika, ohnivaka, vidlaka